version: 2
plugins:
  eslint:
    enabled: true
  fixme:
     enabled: true
     config:
       strings:
       - TODO
       - FIXME
       - BUG
  git-legal:
    enabled: true

exclude_patterns:
  - "public/tests/**"
  - "scripts/**"
  - "manual/**"
  - "contracts/**"

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 500
  method-complexity:
    enabled: true
    config:
      threshold: 15
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 100
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
