FROM mhart/alpine-node:10

# MAINTAINER Alex Step <alex.step@dao.casino>



WORKDIR /bankroller

COPY package.json .
COPY tsconfig.json .
COPY lerna.json .
COPY ./packages/bankroller-core ./packages/bankroller-core
COPY ./packages/dc-core ./packages/dc-core
COPY ./packages/dc-configs ./packages/dc-configs
COPY ./packages/dc-logging ./packages/dc-logging
COPY ./packages/dc-ethereum-utils ./packages/dc-ethereum-utils
COPY ./packages/dc-messaging ./packages/dc-messaging

RUN apk add --no-cache make gcc g++ python git bash && \
    npm i -g yarn && \ 
    yarn global add lerna && \
    npm i -g nodemon typescript

# The global package.json only contains build dependencies

COPY ./scripts ./scripts

RUN yarn install --production=true && yarn build:ts

ENV DC_NETWORK=ropsten

CMD ["node", "./packages/bankroller-core/lib/index.js"]